### ISSUE TITLE
分享mnga链接到微信无法直接拉起app

### ISSUE THREAD

**Issue by imakid** [BugenZhao/MNGA#100]
mnga链接分享无法直接拉起app，只能通过在微信里跳转到默认浏览器才可以打开app。

另外，无论是走mnga分享，还是nga分享，在微信里到样式都比较简单，如果可以看到标题预览就更好了。

感谢做出了优秀的nga客户端给大家使用🙏

**Comment by BugenZhao** [comment]
你好，这个功能需要与微信官方注册接入，个人制作的第三方客户端暂时不会选择接入，请您理解。
