### ISSUE TITLE
MacOS 下的TestFlight已经上线，希望macos版能够发布

### ISSUE THREAD

**Issue by GuryYu** [BugenZhao/MNGA#103]
MacOS 下的TestFlight已经上线，自己编译的门槛比较高，希望能有预编译的版本发布

**Comment by yanyin1986** [comment]
我本地试着编译了一下，编过去了。
本地的环境的话：
```
$cargo lipo -V
cargo-lipo 3.2.0
```
--profile 选项被删除了，需要改成 --release

一些swift代码在macos下面是跑不过去的。

**Comment by hevi1991** [comment]
> 我本地试着编译了一下，编过去了。 本地的环境的话：
> 
> ```
> $cargo lipo -V
> cargo-lipo 3.2.0
> ```
> 
> `--profile` 选项被删除了，`--profile production` 改成 `--release` 就跑过去了。
> 
> 上面的操作造成了 `create-xcframework` 的路径也不对了，改成下面的就可以用了
> 
> ```
> xcodebuild -create-xcframework \
>   -library target/universal/release/liblogic.a \
>   -headers out/include/* \
>   -output out/logic-macos.xcframework
> ```
> 
> 还有一些swift代码在macos下面是跑不过去的。 最近比较忙，下班之后把 rust的编译做个PR上来。

之前折腾了好多次编译，macOS都编译不出来，明明文件都在，就是提示无法找到作者写的rust那部分代码，配置里头调了框架依赖也不行。

环境是 macbook 2019 xcode 和 rust 版本为近期最新的稳定版。

伸手摸鱼党求大佬编译一份intel的。

谢谢大佬

**Comment by yanyin1986** [comment]
@hevi1991 
步骤是这样的：

```shell
git clone git@github.com:BugenZhao/MNGA.git
cd MNGA

brew install swift-protobuf
cargo install cargo-lipo
rustup target add aarch64-apple-ios
rustup target add aarch64-apple-darwin
rustup target add x86_64-apple-darwin

# 生成PB
protoc --swift_out=app/Shared/Protos/ --swift_opt=Visibility=Public -I protos/ protos/*.proto

# 编译mac下的 universal 的库（x86_64 + arm64）
cargo lipo --package logic --targets x86_64-apple-darwin aarch64-apple-darwin --release
# 打包 xcframework
xcodebuild -create-xcframework -library target/universal/release/liblogic.a -output out/logic-macos.xcframework
```

**Comment by hevi1991** [comment]
> @hevi1991 步骤是这样的：
> 
> ```shell
> git clone git@github.com:BugenZhao/MNGA.git
> cd MNGA
> 
> # 安装一些依赖
> brew install swift-protobuf
> cargo install cargo-lipo
> rustup target add aarch64-apple-ios
> rustup target add aarch64-apple-darwin
> rustup target add x86_64-apple-darwin
> 
> # 生成PB
> protoc --swift_out=app/Shared/Protos/ --swift_opt=Visibility=Public -I protos/ protos/*.proto
> 
> # 编译mac下的 universal 的库（x86_64 + arm64）
> cargo lipo --package logic --targets x86_64-apple-darwin aarch64-apple-darwin --release
> # 打包 xcframework
> xcodebuild -create-xcframework -library target/universal/release/liblogic.a -output out/logic-macos.xcframework
> ```

还是不行，报SwiftUIX相关的错误

![pic](https://i.imgur.com/DRT2vkL.png)

**Comment by yanyin1986** [comment]
是的，这个是 `SwiftUIX` 的问题=。=
https://github.com/SwiftUIX/SwiftUIX

这个解决了的话，还有一大堆报错。
早上弄了一个编译不出错的版本，我fork一下吧。

**Comment by yanyin1986** [comment]
@hevi1991 
https://github.com/yanyin1986/MNGA

`SwiftUIX` 的那个问题的话，你可以用vim强行修改一下这个文件，加2句话，至少编译可以过。
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/1109143/157399417-18877534-ea8d-491b-994b-55a9dc5541bf.png">

L38
FROM
`self.init(data, selection: selection, rowContent: { element  in`
TO
`self.init(data, selection: selection, rowContent: { element, _  in`

L49 也差不多。

**Comment by BugenZhao** [comment]
MNGA此前的开发模式一直是iOS为主，所以一般不能保证macOS编译成功😢。考虑到macOS Native版体验比较一般，建议各位如果是M1芯片，直接使用iOS版本。

**Comment by ununian** [comment]
> MNGA此前的开发模式一直是iOS为主，所以一般不能保证macOS编译成功😢。考虑到macOS Native版体验比较一般，建议各位如果是M1芯片，直接使用iOS版本。

但是没法打包成.app来使用呀，或者麻烦传一下最新版到app store吧，TestFlight 显示不能加人了

**Comment by BugenZhao** [comment]
> 但是没法打包成.app来使用呀，或者麻烦传一下最新版到app store吧，TestFlight 显示不能加人了

你好，已经在 App Store 上架了：
https://apps.apple.com/us/app/mnga-nga-%E7%A4%BE%E5%8C%BA%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BC%80%E6%BA%90%E5%AE%A2%E6%88%B7%E7%AB%AF/id1586461246

**Comment by ununian** [comment]
> > 但是没法打包成.app来使用呀，或者麻烦传一下最新版到app store吧，TestFlight 显示不能加人了
> 
> 你好，已经在 App Store 上架了： [apps.apple.com/us/app/mnga-nga-%E7%A4%BE%E5%8C%BA%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BC%80%E6%BA%90%E5%AE%A2%E6%88%B7%E7%AB%AF/id1586461246](https://apps.apple.com/us/app/mnga-nga-%E7%A4%BE%E5%8C%BA%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BC%80%E6%BA%90%E5%AE%A2%E6%88%B7%E7%AB%AF/id1586461246)

我看app store版本更新是1年前，但是代码仓库是4个月前，这个没区别吗？
