### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by NULL-2333** [BugenZhao/MNGA#107]
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/20411456/159279719-483fde21-dde0-4810-ba24-3880ca5403e9.png">
电脑系统是12.0.1，Xcode 13.3，模拟器真机都编译不过

**Comment by BugenZhao** [comment]
请在最新的main分支上尝试一下？如果仍然有问题请随意reopen。
