### ISSUE TITLE
希望能支持 iOS14

### ISSUE THREAD

**Issue by Tyrone2333** [BugenZhao/MNGA#110]
目前用 iPhone8 在 iOS14 做备用机,升级 15 系统会卡,为什么最低支持15呢,是用了什么新特性吗?

**Comment by theblueandblackcrow** [comment]
对于开发者来说，ios15出了14没有的功能

**Comment by Tyrone2333** [comment]
72 iOS 15
 26 iOS 14
 2 Earlier

 iOS 15 只有72的占有率, 兼容一下14还是有必要的吧. 我有下载改 target 到14编译, 会报14不可用的api错误, 但是我是前端不懂 swift 代码没法改😭

**Comment by BugenZhao** [comment]
本 App 使用了 SwiftUI 3.0 的 API，这些 API 仅限于 iOS 15+ 使用。如果有 iOS 14 的需求可以考虑在 commit 记录中找到较旧的版本尝试。
