### ISSUE TITLE
作者你好，能整理下接口文档吗，我抓过nga的接口，但都有签名，不知道签名是怎么生成的

### ISSUE THREAD

**Issue by keluokeda** [BugenZhao/MNGA#116]

**Comment by keluokeda** [comment]
我也想做一个nga练练手

**Comment by BugenZhao** [comment]
MNGA 是前后端分离的，Rust 后端（`logic` 目录下）把 NGA 的大多数接口封装成了干净清晰的 Protobuf Service，并且带有注释，可以直接用这个。

https://github.com/BugenZhao/MNGA/blob/58e9d1b4a83c6f6f35489897ee3e9d9b2fac786c/protos/Service.proto#L52-L66

如果真的想用原始 API 开发的话🤣，可以参考：
- https://bbs.nga.cn/read.php?tid=6406100
- https://github.com/AgMonk/nga-api

**Comment by keluokeda** [comment]
十分感谢
