### ISSUE TITLE
iPad客户端闪退

### ISSUE THREAD

**Issue by happyTonakai** [BugenZhao/MNGA#117]
复现过程：
点进一个板块 - 点进一个主题 - 手动杀后台（或者等待被iPadOS系统杀后台） - 重新打开mnga

此时由于我们之前点进了一个主题，因此进去的页面左上角显示的是板块的名称，如图所示

![1](https://user-images.githubusercontent.com/21305646/172148098-5efd27d5-bd88-40b3-b93f-a9d23188388e.jpeg)

这时从左侧屏幕边缘向右滑动以返回到板块列表，就会100%闪退，闪退1到2次后，左上角不再显示板块名称，而是显示“返回”二字，这时候才能正常返回，如图所示

![2](https://user-images.githubusercontent.com/21305646/172148263-e23f35b5-7058-4401-b0f3-6e8e6a4cb418.jpeg)

TestFlight和AppStore版本都是如此，也卸载重装过多次没用

**Comment by happyTonakai** [comment]
app version 1.1 (54)，iPadOS 15.3.1
使用相同版本app在iOS 15.3.1下没这个问题，每次启动都在板块选择页面上

**Comment by BugenZhao** [comment]
你好，最新 TestFlight 版本（v1.2.0，要求 iOS 26）重构了 iPad 下的导航逻辑，应该已修复该问题，欢迎体验。
