### ISSUE TITLE
进入特定子版块导致 App 卡住并闪退

### ISSUE THREAD

**Issue by Boycottangent** [BugenZhao/MNGA#18]
_tf内提交了反馈但没动静，来这边提个iss_

试图进入猴区的 `视频网站于up主讨论` 子版块时，整个 app 会卡住无响应很长时间，并最终闪退，很奇怪的是其他的子版块没有这个问题，不确定是不是 bug

**Comment by BugenZhao** [comment]
TestFlight 的反馈之前已经收到了，在里面没办法回复😂
相关问题还有在子版块页面长按一项（但什么都不用做）就会导致主页面卡住一段时间，具体原因还都没有定位到，或许可以考虑绕过这种操作逻辑。

**Comment by Boycottangent** [comment]
我现在发现并不是特定操作的问题，而是这个子版块本身可能有什么问题，我从二级页面进去也会卡

**Comment by Boycottangent** [comment]
尝试调查了一下，视频与up主这个板块的特殊性在于它是用户 `此生冬马` 的个人版面，我在MNGA里尝试了其他个人版面，发现都会导致这个问题

**Comment by Boycottangent** [comment]
iPhone12 mini
iOS 14.8
App 版本是1.0(11) TF最新版

**Comment by BugenZhao** [comment]
好的，我找机会测试下。另外闪退的时候应该会有TestFlight的“已崩溃”提示吧，可以提交一下崩溃信息方便分析😁
