### ISSUE TITLE
有个帖子一直不显示正文

### ISSUE THREAD

**Issue by stefanielyq** [BugenZhao/MNGA#5]
![114ed8b4a28d64fa0641c4b0823bb84](https://user-images.githubusercontent.com/16235150/135014817-37d14efa-457c-48b2-8777-15492aa1a6f2.png)
试过wifi和流量 也刷新过好几次了。。。
报了一次错 但是没截到图-。-

**Comment by BugenZhao** [comment]
这个是折叠的内容，默认采用了遮盖的折叠风格（设置-折叠风格），点一下“前情提要”就可以显示出来了。

默认用遮盖风格确实不太合理，后续会修改成“隐藏”风格。

**Comment by stefanielyq** [comment]
好咧~懂了~
