### ISSUE TITLE
 在主界面点击切换”所有板块“和”只看收藏“失效

### ISSUE THREAD

**Issue by KasumigaokaUtaha** [BugenZhao/MNGA#6]
系统：iOS 14.4
问题：在主界面时，点击右上角图标，在弹出的选项中切换”只看收藏“和”所有板块“后并没有生效，比如当前选择的是”所有板块“，点击”只看收藏“后，主界面并没有执行对应的切换，但是如果点击”编辑收藏“的话，之前的切换就生效了。

**Comment by BugenZhao** [comment]
感谢反馈，过两天我用iOS 14的机器复现一下。

版块页面显示模式是持久化的，这段时间你可以继续通过这个workaround来设置 :D

**Comment by KasumigaokaUtaha** [comment]
哈哈哈哈，好的好的。

另外还有一个问题，目前这个项目支持macOS吗？我刚才拿Xcode 13给macOS编译遇到好几个bug。

**Comment by BugenZhao** [comment]
很久以前是支持的，后来因为维护太麻烦，并且很难做到纯 Swift UI（引入了一些 UIKit 的代码）就暂时放弃了😢

不过理论上大多数代码都是能复用的，开发时候也尽可能考虑到了。只是某些 iOS Only 的 Swift UI API 可能需要加一些条件编译的修改，某些依赖 UIKit 的 feature 需要重写~或者注释掉~（例如发帖的编辑器），工作量不大但也不算低。

其实可以考虑整一下 macOS Catalyst 直接跑 iOS 的 UI，不过 Rust 侧在 catalyst 下似乎有些问题（运行时 exception），就暂时没再折腾。

**Comment by KasumigaokaUtaha** [comment]
啊，已经是很久以前了吗？我翻提交记录就翻了一页的时候看到了一个添加 macOS 支持的提交。

不过我目前遇到的错误是编译一个第三方库 SwiftUIX 的时候发生的，看上去是 Swift Compiler 没找到对应的 SwfitUI 的某个类的构造器导致的。不过可能这个问题解决了之后就会遇到你说的那些 iOS 和 macOS 提供的 API 不一致的问题吧。

Catalyst 需要额外再做什么改动吗？之前只是有听说过这个没仔细了解过。

**Comment by KasumigaokaUtaha** [comment]
貌似找到了原因了，从 iOS 14.5 开始 ObservableObject 里被标记为 AppStorage 的变量会正确的发出 objectWillChange。但是我的系统刚好是在 iOS 14.4 hhhhhh。

[AppStorage property wrappers now work as expected when contained inside an ObservableObject, causing the system to emit the objectWillChange publisher. (65562845)](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14_5-release-notes)

**Comment by BugenZhao** [comment]
Swift 编译器不一定能一次性报出所有错，macOS target 编译应该还是存在大量错误的😢

Catalyst 就相当于在 macOS 10.15+ 上跑 iOS UIKit，需要一个全新的 abi，目前遇到的问题主要是 Rust logic 侧没办法正常运行。

**Comment by BugenZhao** [comment]
> 啊，已经是很久以前了吗？我翻提交记录就翻了一页的时候看到了一个添加 macOS 支持的提交。
> 
> 不过我目前遇到的错误是编译一个第三方库 SwiftUIX 的时候发生的，看上去是 Swift Compiler 没找到对应的 SwfitUI 的某个类的构造器导致的。不过可能这个问题解决了之后就会遇到你说的那些 iOS 和 macOS 提供的 API 不一致的问题吧。
> 
> Catalyst 需要额外再做什么改动吗？之前只是有听说过这个没仔细了解过。

经过 PR https://github.com/BugenZhao/MNGA/pull/16 后，macOS Target 已经可以正常编译并运行最基本的一些功能了🚀

**Comment by KasumigaokaUtaha** [comment]
> > 啊，已经是很久以前了吗？我翻提交记录就翻了一页的时候看到了一个添加 macOS 支持的提交。
> > 不过我目前遇到的错误是编译一个第三方库 SwiftUIX 的时候发生的，看上去是 Swift Compiler 没找到对应的 SwfitUI 的某个类的构造器导致的。不过可能这个问题解决了之后就会遇到你说的那些 iOS 和 macOS 提供的 API 不一致的问题吧。
> > Catalyst 需要额外再做什么改动吗？之前只是有听说过这个没仔细了解过。
> 
> 经过 PR #16 后，macOS Target 已经可以正常编译并运行最基本的一些功能了🚀

强 大佬 强

让我看看这是怎么实现的😃
