### ISSUE TITLE
如果想Contribute的话，是不是可以无视这个License的问题呀？

### ISSUE THREAD

**Issue by yanyin1986** [BugenZhao/MNGA#87]
https://github.com/BugenZhao/MNGA/blob/27194c7c24341fee72a84c1829ef4402521aac69/README.md?plain=1#L103

**Comment by BugenZhao** [comment]
可以的，本意是为了避免修改代码然后重新分发（如抢先上架Store）之类的行为，我稍后改下，contribute很欢迎！

**Comment by yanyin1986** [comment]
好的，那当前issue我先关掉。
