### ISSUE TITLE
建议把每个账号的注册时间戳前添加“注册时间”的前缀

### ISSUE THREAD

**Issue by macvis** [BugenZhao/MNGA#97]
因为每次截图分享出去的时候总有人问这发帖时间咋都是几年前十几年前的
这客户端目前装机量应该不高，所以 ui 不太熟，楼主层主title 里的时间戳容易被当成发帖时间
建议增加一个前缀，以消除误解

**Comment by BugenZhao** [comment]
@macvis 感谢反馈，新版本已默认关闭显示注册时间，可在设置中调节。

**Comment by macvis** [comment]
> 

刚看到上架 app store 了，安利了好多人安装
